import { useEffect,useState } from 'react';
import { ActivityIndicator,Alert,FlatList,Pressable,SafeAreaView,StyleSheet,Text,View } from 'react-native';
import { router,useLocalSearchParams } from 'expo-router';
import { deleteDoc,doc,getDoc } from 'firebase/firestore';
import { auth,db } from '../../lib/firebase'; import BottomNav from '../../components/BottomNav'; import LitIcon from '../../components/LitIcon'; import { getNativeGroupForumDisplay } from '../../services/groupDisplay'; import { BRAND } from '../../../shared/brand';
export default function Group(){const p=useLocalSearchParams(),id=String(p.groupId||''),name=String(p.name||'Group'),role=String(p.role||'');const[posts,setPosts]=useState([]),[loading,setLoading]=useState(true),[h,setH]=useState(0),[idx,setIdx]=useState(0);const manage=['owner','admin','moderator'].includes(role.toLowerCase());
async function load(){try{setLoading(true);const g=await getDoc(doc(db,'groups',id));if(g.exists()&&g.data()?.type==='class'){router.replace({pathname:'/class/[classId]',params:{classId:id,name:g.data()?.name||name,role}});return}setPosts(await getNativeGroupForumDisplay(id))}finally{setLoading(false)}} useEffect(()=>{load()},[id]);
function leave(){Alert.alert('Leave Group',`Leave “${name}”?`,[{text:'Cancel',style:'cancel'},{text:'Leave',style:'destructive',onPress:async()=>{await deleteDoc(doc(db,'groups',id,'members',auth.currentUser.uid));router.replace('/groups')}}])}
if(loading)return <SafeAreaView style={s.safe}><ActivityIndicator style={{marginTop:80}}/></SafeAreaView>;return <SafeAreaView style={s.safe}><View style={s.header}><View style={s.row}><Pressable onPress={()=>router.replace('/groups')}><Text style={s.link}>‹ Groups</Text></Pressable><View style={s.row}><Pressable onPress={()=>router.push({pathname:'/group/new-discussion',params:{groupId:id,name,role}})}><Text style={s.link}>+ Discussion</Text></Pressable><Pressable onPress={manage?()=>router.push({pathname:'/group/settings',params:{groupId:id,name,role}}):leave}><Text style={manage?s.link:s.leave}>{manage?'Settings':'Leave'}</Text></Pressable></View></View><Text style={s.title}>{name}</Text><Text style={s.muted}>Swipe vertically between discussions</Text></View><View style={s.viewport} onLayout={e=>setH(Math.floor(e.nativeEvent.layout.height))}>{h?<FlatList data={posts} keyExtractor={x=>String(x.id)} snapToInterval={h} decelerationRate="fast" disableIntervalMomentum onMomentumScrollEnd={e=>setIdx(Math.round(e.nativeEvent.contentOffset.y/Math.max(h,1)))} renderItem={({item})=><View style={[s.page,{height:h}]}><Pressable style={s.card} onPress={()=>router.push({pathname:'/group/post',params:{groupId:id,postId:item.id,title:item.title||'Discussion',body:item.body||item.note||'',name,role,userId:item.userId||item.authorId||'',authorName:item.authorName||item.displayName||item.username||''}})}><Text style={s.kicker}>GROUP DISCUSSION</Text><Text style={s.postTitle}>{item.title||'Discussion'}</Text><Text style={s.muted}>{item.authorName||item.displayName||item.username?'Posted by '+(item.authorName||item.displayName||item.username):'Posted by Reader'}</Text>{item.body?<Text numberOfLines={12} style={s.body}>{item.body}</Text>:null}<View style={s.votes}><View style={s.row}><LitIcon name="link" size={20}/><Text>{Number(item.forumUpCount||0)}</Text></View><Text style={s.score}>{Number(item.forumScore||0)}</Text><View style={s.row}><LitIcon name="unlink" size={20}/><Text>{Number(item.forumDownCount||0)}</Text></View></View><Text style={s.hint}>Tap to open discussion ›</Text></Pressable></View>}/>:null}</View><BottomNav active="groups"/></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:BRAND.background},header:{padding:16,backgroundColor:BRAND.surface,borderBottomWidth:1,borderBottomColor:BRAND.line},row:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:14},link:{color:BRAND.tealDark,fontWeight:'900'},leave:{color:BRAND.danger,fontWeight:'900'},title:{fontSize:26,fontWeight:'900',color:BRAND.ink,marginTop:7},muted:{color:BRAND.muted,marginTop:4},viewport:{flex:1},page:{padding:16},card:{flex:1,padding:22,borderRadius:22,borderWidth:1,borderColor:BRAND.line,backgroundColor:BRAND.surface},kicker:{color:BRAND.tealDark,fontSize:10,fontWeight:'900'},postTitle:{fontSize:24,fontWeight:'900',color:BRAND.ink,marginTop:10},body:{color:BRAND.muted,lineHeight:21,marginTop:16},votes:{marginTop:'auto',flexDirection:'row',justifyContent:'space-between',alignItems:'center'},score:{fontWeight:'900',color:BRAND.ink},hint:{color:BRAND.muted,textAlign:'center',marginTop:14}});
