import { useEffect,useRef,useState } from "react";
import { ActivityIndicator,FlatList,PanResponder,Pressable,SafeAreaView,StyleSheet,Text,View } from "react-native";
import { router,useLocalSearchParams } from "expo-router";
import BottomNav from "../../components/BottomNav";import { getNativeGroupForum } from "../../services/social";import { BRAND } from "../../../shared/brand";
export default function Group(){const p=useLocalSearchParams(),id=String(p.groupId||""),name=String(p.name||"Group"),role=String(p.role||"");const [posts,setPosts]=useState([]),[loading,setLoading]=useState(true);useEffect(()=>{getNativeGroupForum(id).then(setPosts).finally(()=>setLoading(false));},[id]);const manage=["owner","admin","moderator","teacher"].includes(role.toLowerCase());
function open(x){router.push({pathname:"/group/post",params:{groupId:id,postId:x.id,title:x.title||"Discussion",body:x.body||"",name,role}});}
if(loading)return <SafeAreaView style={s.safe}><View style={s.center}><ActivityIndicator size="large"/></View></SafeAreaView>;
return <SafeAreaView style={s.safe}><View style={s.header}><Pressable onPress={()=>router.replace("/groups")}><Text style={s.back}>‹ Groups</Text></Pressable><Text style={s.title}>{name}</Text>{manage&&<Pressable onPress={()=>router.push({pathname:"/group/settings",params:{groupId:id,name,role}})}><Text style={s.settings}>Settings & Moderation</Text></Pressable>}</View><FlatList data={posts} keyExtractor={x=>x.id} pagingEnabled showsVerticalScrollIndicator={false} renderItem={({item})=><Post x={item} open={()=>open(item)}/>} /><BottomNav active="groups"/></SafeAreaView>;}
function Post({x,open}){const pan=useRef(PanResponder.create({onMoveShouldSetPanResponder:(_,g)=>Math.abs(g.dx)>18&&Math.abs(g.dx)>Math.abs(g.dy),onPanResponderRelease:(_,g)=>{if(g.dx<-60)open();else if(g.dx>60)router.back();}})).current;return <View style={s.page} {...pan.panHandlers}><Pressable onPress={open} style={s.card}><Text style={s.postTitle}>{x.title||"Discussion"}</Text>{!!x.body&&<Text numberOfLines={8} style={s.body}>{x.body}</Text>}<Text style={s.hint}>Swipe left or tap to open · right to go back</Text></Pressable></View>;}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:BRAND.background},center:{flex:1,alignItems:"center",justifyContent:"center"},header:{backgroundColor:BRAND.surface,padding:18,borderBottomWidth:1,borderBottomColor:BRAND.line},back:{color:BRAND.tealDark,fontWeight:"900"},title:{color:BRAND.ink,fontSize:26,fontWeight:"900",marginTop:8},settings:{color:BRAND.tealDark,fontWeight:"900",marginTop:12},page:{minHeight:560,padding:20,justifyContent:"center"},card:{backgroundColor:BRAND.surface,borderWidth:1,borderColor:BRAND.line,borderRadius:22,padding:22},postTitle:{color:BRAND.ink,fontSize:22,fontWeight:"900"},body:{color:BRAND.muted,lineHeight:21,marginTop:10},hint:{color:BRAND.muted,fontSize:11,textAlign:"center",marginTop:18}});
