import { useEffect,useMemo,useRef,useState } from "react";
import { ActivityIndicator,FlatList,Image,PanResponder,Pressable,SafeAreaView,StyleSheet,Text,TextInput,View } from "react-native";
import { router } from "expo-router";
import AppHeader from "../components/AppHeader";import BottomNav from "../components/BottomNav";import { getNativeGroups } from "../services/social";import { groupAvatarUrl } from "../../shared/groupAvatars";import { BRAND } from "../../shared/brand";
const V=[["mine","My Groups"],["classes","My Classes"],["discoverable","Discover"]];
export default function Groups(){const [b,setB]=useState({mine:[],classes:[],discoverable:[]}),[view,setView]=useState("mine"),[q,setQ]=useState(""),[loading,setLoading]=useState(true);useEffect(()=>{getNativeGroups().then(setB).finally(()=>setLoading(false));},[]);
const groups=useMemo(()=>{const src=b[view]||[],t=q.trim().toLowerCase();return t?src.filter(g=>[g.name,g.description,g.type].filter(Boolean).some(x=>String(x).toLowerCase().includes(t))):src;},[b,view,q]);
function open(g){router.push({pathname:"/group/[groupId]",params:{groupId:g.id,name:g.name||"Group",role:g.membership?.role||""}});}
if(loading)return <SafeAreaView style={s.safe}><View style={s.center}><ActivityIndicator size="large"/></View></SafeAreaView>;
return <SafeAreaView style={s.safe}><AppHeader title="Groups" subtitle="Swipe vertically to browse · left to open"/><View style={s.tabs}>{V.map(([id,l])=><Pressable key={id} onPress={()=>setView(id)} style={[s.tab,view===id&&s.tabA]}><Text style={[s.tabT,view===id&&s.tabTA]}>{l}</Text></Pressable>)}</View><TextInput value={q} onChangeText={setQ} placeholder="Search groups..." style={s.search}/>
<FlatList data={groups} keyExtractor={x=>x.id} pagingEnabled showsVerticalScrollIndicator={false} renderItem={({item})=><Card g={item} open={()=>open(item)}/>} /><BottomNav active="groups"/></SafeAreaView>;}
function Card({g,open}){const pan=useRef(PanResponder.create({onMoveShouldSetPanResponder:(_,x)=>Math.abs(x.dx)>18&&Math.abs(x.dx)>Math.abs(x.dy),onPanResponderRelease:(_,x)=>{if(x.dx<-60)open();}})).current,a=groupAvatarUrl(g.avatar);return <View style={s.page} {...pan.panHandlers}><Pressable onPress={open} style={s.card}>{!!a&&<Image source={{uri:a}} style={s.avatar}/>}<Text style={s.eyebrow}>{g.type==="class"?"CLASS":"READING GROUP"}</Text><Text style={s.title}>{g.name||"Group"}</Text>{!!g.description&&<Text style={s.desc}>{g.description}</Text>}<Text style={s.meta}>{g.membership?.role||"Member"}</Text><Text style={s.hint}>Swipe left or tap to open</Text></Pressable></View>;}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:BRAND.background},center:{flex:1,alignItems:"center",justifyContent:"center"},tabs:{flexDirection:"row",gap:6,padding:10,backgroundColor:BRAND.surface},tab:{flex:1,paddingVertical:9,borderRadius:999,borderWidth:1,borderColor:BRAND.line,alignItems:"center"},tabA:{backgroundColor:BRAND.teal},tabT:{color:BRAND.muted,fontWeight:"800",fontSize:12},tabTA:{color:"#FFF"},search:{margin:10,minHeight:44,borderWidth:1,borderColor:BRAND.line,backgroundColor:BRAND.surface,borderRadius:14,paddingHorizontal:14},page:{minHeight:560,padding:20,justifyContent:"center"},card:{backgroundColor:BRAND.surface,borderWidth:1,borderColor:BRAND.line,borderRadius:24,padding:24},avatar:{width:84,height:84,borderRadius:18,marginBottom:16},eyebrow:{color:BRAND.tealDark,fontWeight:"900",fontSize:11},title:{color:BRAND.ink,fontSize:28,fontWeight:"900",marginTop:8},desc:{color:BRAND.muted,lineHeight:21,marginTop:10},meta:{color:BRAND.tealDark,fontWeight:"800",marginTop:16},hint:{color:BRAND.muted,textAlign:"center",marginTop:20,fontSize:11}});
