import { useEffect,useMemo,useState } from 'react';
import { ActivityIndicator,FlatList,Image,Modal,Pressable,SafeAreaView,StyleSheet,Text,TextInput,View } from 'react-native';
import { router } from 'expo-router';
import { signOut } from 'firebase/auth';
import AppHeader from '../components/AppHeader'; import BottomNav from '../components/BottomNav';
import { getNativeLibraryBundle } from '../services/library';
import { cancelNativeFriendRequest,removeNativeFriend,respondNativeFriendRequest,searchNativeReadersByUsername,sendNativeFriendRequest } from '../services/librarySocial';
import { LIBRARY_TABS } from '../../shared/libraryTabs'; import { profileAvatarUrl } from '../../shared/profileAvatars'; import { groupAvatarUrl } from '../../shared/groupAvatars'; import { BRAND } from '../../shared/brand'; import { auth } from '../lib/firebase';
export default function Library(){const[tab,setTab]=useState('timeline'),[bundle,setBundle]=useState(null),[loading,setLoading]=useState(true),[modal,setModal]=useState(false),[q,setQ]=useState(''),[results,setResults]=useState([]),[status,setStatus]=useState(''),[searching,setSearching]=useState(false);
async function load(){try{setLoading(true);setBundle(await getNativeLibraryBundle())}finally{setLoading(false)}} useEffect(()=>{load()},[]);
const items=useMemo(()=>{if(!bundle)return[];if(tab==='timeline')return bundle.timeline||[];if(tab==='journal')return bundle.journal||[];if(tab==='friends')return bundle.friends||[];if(tab==='groups')return bundle.groups||[];return[...(bundle.savedBooks||[]).map(x=>({...x,savedType:'book'})),...(bundle.savedChain||[]).map(x=>({...x,savedType:'chain'}))]},[bundle,tab]);
function open(item){if(tab==='friends'){router.push({pathname:'/profile/[userId]',params:{userId:String(item.otherUserId||item.userId||item.id)}});return}if(tab==='groups'){router.push({pathname:item.type==='class'?'/class/[classId]':'/group/[groupId]',params:item.type==='class'?{classId:item.id,name:item.name||'Class',role:item.membership?.role||''}:{groupId:item.id,name:item.name||'Group',role:item.membership?.role||''}});return}if(tab==='journal'){router.push({pathname:'/journal/[entryId]',params:{entryId:item.id}});return}if(tab==='timeline'||(tab==='saved'&&item.savedType==='book'))router.push({pathname:'/reader/[bookId]',params:{bookId:String(item.bookId||item.id),title:item.title||'Book',author:item.author||''}})}
async function search(){const t=q.trim();if(t.length<2){setStatus('Enter at least 2 characters.');return}try{setSearching(true);setStatus('');const r=await searchNativeReadersByUsername(t,15);const mine=new Set((bundle?.friends||[]).map(x=>String(x.otherUserId||x.id)));const self=String(bundle?.profile?.id||'');setResults(r.filter(x=>String(x.userId||x.id)!==self&&!mine.has(String(x.userId||x.id))))}catch(e){setStatus(e?.message||'Could not search.')}finally{setSearching(false)}}
async function add(x){await sendNativeFriendRequest(x.userId||x.id);setResults(r=>r.filter(y=>String(y.userId||y.id)!==String(x.userId||x.id)));setStatus('Friend request sent.');await load()}
if(loading)return <SafeAreaView style={s.safe}><ActivityIndicator style={{marginTop:80}} size="large"/></SafeAreaView>;
return <SafeAreaView style={s.safe}><AppHeader title="Library" subtitle={bundle?.profile?.displayName||bundle?.profile?.username||'Your Lit Chain'}/><View style={s.tabs}>{LIBRARY_TABS.map(x=><Pressable key={x.id} onPress={()=>setTab(x.id)} style={[s.tab,tab===x.id&&s.tabOn]}><Text style={[s.tabText,tab===x.id&&s.tabTextOn]}>{x.label}</Text></Pressable>)}</View>
<FlatList data={items} key={tab} keyExtractor={(x,i)=>`${tab}_${x.id||i}`} contentContainerStyle={s.list} ListHeaderComponent={<>{tab==='timeline'&&<View style={s.actions}><Pressable style={s.button} onPress={()=>router.push('/profile/edit')}><Text style={s.buttonText}>Edit Profile</Text></Pressable><Pressable style={s.outline} onPress={async()=>{await signOut(auth);router.replace('/login')}}><Text style={s.outlineText}>Sign Out</Text></Pressable></View>}{tab==='friends'&&<Pressable style={s.button} onPress={()=>{setModal(true);setStatus('');setResults([])}}><Text style={s.buttonText}>+ Find Reader</Text></Pressable>}</>} renderItem={({item})=>{const fimg=tab==='friends'?(profileAvatarUrl(item.avatar)||item.photoURL||''):'';const gimg=tab==='groups'?groupAvatarUrl(item.avatar):'';return <Pressable onPress={()=>open(item)} style={s.card}>{fimg?<Image source={{uri:fimg}} style={s.avatar}/>:null}{gimg?<Image source={{uri:gimg}} style={s.groupAvatar}/>:null}<Text style={s.eyebrow}>{tab==='groups'?(item.type==='class'?'CLASS':'GROUP'):tab.toUpperCase()}</Text><Text style={s.title}>{item.title||item.name||item.displayName||item.username||'Lit Chain item'}</Text>{item.author?<Text style={s.muted}>{item.author}</Text>:null}{tab==='friends'?<View style={s.friendRow}><Text style={s.detail}>Tap to view profile</Text><Pressable onPress={async e=>{e.stopPropagation?.();await removeNativeFriend(item.otherUserId||item.id);await load()}}><Text style={s.remove}>Remove</Text></Pressable></View>:null}{tab==='groups'?<Text style={s.detail}>{item.type==='class'?'Class':item.membership?.role||'Reading Group'} · Tap to open</Text>:null}{tab==='timeline'?<Text style={s.detail}>{Math.round(Number(item.percentComplete)||0)}% complete · Tap to read</Text>:null}</Pressable>}}/>
<BottomNav active="library"/><Modal visible={modal} animationType="slide" onRequestClose={()=>setModal(false)}><SafeAreaView style={s.safe}><View style={s.modalHead}><Text style={s.title}>Find Reader</Text><Pressable onPress={()=>setModal(false)}><Text style={s.close}>×</Text></Pressable></View><View style={s.searchRow}><TextInput value={q} onChangeText={setQ} autoCapitalize="none" placeholder="Username" style={s.input} onSubmitEditing={search}/><Pressable style={s.button} onPress={search}><Text style={s.buttonText}>{searching?'…':'Search'}</Text></Pressable></View><FlatList data={results} keyExtractor={x=>String(x.userId||x.id)} contentContainerStyle={s.list} renderItem={({item})=>{const img=profileAvatarUrl(item.avatar)||item.photoURL||'';return <View style={s.result}>{img?<Image source={{uri:img}} style={s.resultAvatar}/>:<View style={s.resultFallback}><Text style={s.fallbackText}>{String(item.displayName||item.username||'R')[0].toUpperCase()}</Text></View>}<Pressable style={{flex:1}} onPress={()=>router.push({pathname:'/profile/[userId]',params:{userId:String(item.userId||item.id)}})}><Text style={s.resultName}>{item.displayName||item.username||'Reader'}</Text>{item.username?<Text style={s.muted}>@{item.username}</Text>:null}</Pressable><Pressable style={s.add} onPress={()=>add(item)}><Text style={s.buttonText}>Add</Text></Pressable></View>}}/>{status?<Text style={s.status}>{status}</Text>:null}</SafeAreaView></Modal></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:BRAND.background},tabs:{flexDirection:'row',padding:6,gap:4,backgroundColor:BRAND.surface},tab:{flex:1,minHeight:36,alignItems:'center',justifyContent:'center',borderRadius:999},tabOn:{backgroundColor:BRAND.teal},tabText:{fontSize:10,fontWeight:'800',color:BRAND.muted},tabTextOn:{color:'#fff'},list:{padding:14,paddingBottom:90},actions:{flexDirection:'row',gap:8,marginBottom:12},button:{minHeight:44,paddingHorizontal:14,borderRadius:12,backgroundColor:BRAND.primary,alignItems:'center',justifyContent:'center'},buttonText:{color:'#fff',fontWeight:'900'},outline:{minHeight:44,paddingHorizontal:14,borderRadius:12,borderWidth:1,borderColor:BRAND.line,alignItems:'center',justifyContent:'center'},outlineText:{color:BRAND.ink,fontWeight:'900'},card:{backgroundColor:BRAND.surface,borderWidth:1,borderColor:BRAND.line,borderRadius:18,padding:18,marginBottom:12},avatar:{width:52,height:52,borderRadius:26,marginBottom:10},groupAvatar:{width:60,height:60,borderRadius:14,marginBottom:10},eyebrow:{color:BRAND.tealDark,fontSize:10,fontWeight:'900'},title:{color:BRAND.ink,fontSize:18,fontWeight:'900',marginTop:6},muted:{color:BRAND.muted,marginTop:3},detail:{color:BRAND.tealDark,marginTop:12,fontWeight:'800'},friendRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},remove:{color:BRAND.danger,fontWeight:'900',marginTop:12},modalHead:{padding:18,flexDirection:'row',alignItems:'center',justifyContent:'space-between',backgroundColor:BRAND.surface},close:{fontSize:30,color:BRAND.ink},searchRow:{flexDirection:'row',gap:8,padding:14},input:{flex:1,minHeight:48,borderWidth:1,borderColor:BRAND.line,borderRadius:12,paddingHorizontal:12,backgroundColor:BRAND.surface},result:{flexDirection:'row',alignItems:'center',gap:12,backgroundColor:BRAND.surface,borderWidth:1,borderColor:BRAND.line,borderRadius:14,padding:12,marginBottom:8},resultAvatar:{width:48,height:48,borderRadius:24},resultFallback:{width:48,height:48,borderRadius:24,backgroundColor:BRAND.teal,alignItems:'center',justifyContent:'center'},fallbackText:{color:'#fff',fontWeight:'900'},resultName:{fontWeight:'900',color:BRAND.ink},add:{backgroundColor:BRAND.primary,borderRadius:10,paddingHorizontal:14,paddingVertical:9},status:{padding:14,color:BRAND.tealDark,textAlign:'center'}});
