import { collection,deleteDoc,doc,getDoc,getDocs,orderBy,query,serverTimestamp,setDoc,Timestamp,updateDoc,where,writeBatch } from 'firebase/firestore'; import { auth,db } from '../lib/firebase';
export const PLATFORM_ROLES={MODERATOR:'platform_moderator',ADMIN:'platform_admin',FOUNDATION_ADMIN:'foundation_admin'}; const RANK={user:0,platform_moderator:1,platform_admin:2,foundation_admin:3};
function user(){if(!auth.currentUser)throw new Error('You must be logged in.');return auth.currentUser} function flags(role='user'){const r=RANK[role]||0;return{role,isPlatformModerator:r>=1,isPlatformAdmin:r>=2,isFoundationAdmin:role===PLATFORM_ROLES.FOUNDATION_ADMIN}}
async function profile(id){if(!id)return null;try{const s=await getDoc(doc(db,'publicProfiles',String(id)));return s.exists()?{id:s.id,...s.data()}:null}catch{return null}}
export async function getMyNativePlatformRole(){const u=user(),s=await getDoc(doc(db,'platformRoles',u.uid));return s.exists()?{id:s.id,...s.data(),userId:s.data().userId||u.uid,...flags(s.data().role||'user')}:{userId:u.uid,...flags('user')}}
async function mod(){const r=await getMyNativePlatformRole();if(!r.isPlatformModerator)throw new Error('You do not have platform moderation access.');return r} async function admin(){const r=await mod();if(!r.isPlatformAdmin)throw new Error('Platform administrator access is required.');return r}
export async function getNativePlatformReports(){await mod();let s;try{s=await getDocs(query(collection(db,'moderationReports'),where('status','==','open'),orderBy('createdAtISO','desc')))}catch{s=await getDocs(collection(db,'moderationReports'))}const rows=s.docs.map(x=>({id:x.id,...x.data()})).filter(x=>x.status==='open');return Promise.all(rows.map(async x=>({...x,targetProfile:await profile(x.targetUserId)})))}
export async function resolveNativePlatformReport(id,resolution='resolved'){const u=user();await mod();await updateDoc(doc(db,'moderationReports',String(id)),{status:resolution==='dismissed'?'dismissed':'resolved',resolvedBy:u.uid,resolvedAtISO:new Date().toISOString(),resolvedAt:serverTimestamp()})}
export async function getNativePlatformEnforcements(){await admin();const s=await getDocs(collection(db,'platformEnforcement'));const rows=s.docs.map(x=>({id:x.id,...x.data()})).filter(x=>['warning','suspended','banned'].includes(x.status));return Promise.all(rows.map(async x=>({...x,targetProfile:await profile(x.userId||x.id)})))}
export async function applyNativePlatformEnforcement({targetUserId,status,reason,durationHours=24}){const u=user();await admin();const uid=String(targetUserId||'').trim(),r=String(reason||'').trim();if(!uid||!r)throw new Error('A reason is required.');const now=new Date(),payload={userId:uid,status,reason:r,enforcedBy:u.uid,updatedAtISO:now.toISOString(),updatedAt:serverTimestamp()};if(status==='suspended'){const end=new Date(now.getTime()+Number(durationHours||24)*3600000);payload.durationHours=Number(durationHours||24);payload.endsAtISO=end.toISOString();payload.endsAt=Timestamp.fromDate(end)}await setDoc(doc(db,'platformEnforcement',uid),payload,{merge:true})}
export async function clearNativePlatformEnforcement(targetUserId){const u=user();await admin();const uid=String(targetUserId||'').trim();const ref=doc(db,'platformEnforcement',uid),snap=await getDoc(ref);if(!snap.exists())throw new Error('No active enforcement record was found.');await updateDoc(ref,{status:'cleared',clearedBy:u.uid,clearedAtISO:new Date().toISOString(),durationHours:null,endsAtISO:null,endsAt:null,updatedAt:serverTimestamp()})}
export async function getNativePlatformAppeals(){await mod();const s=await getDocs(collection(db,'moderationAppeals'));const rows=s.docs.map(x=>({id:x.id,...x.data()})).filter(x=>x.status==='open').sort((a,b)=>String(b.createdAtISO||'').localeCompare(String(a.createdAtISO||'')));return Promise.all(rows.map(async x=>({...x,appellantProfile:await profile(x.appellantUserId)})))}
export async function reviewNativePlatformAppeal({appealId,decision,reviewReason}){const u=user();await admin();const d=decision==='approved'?'approved':decision==='denied'?'denied':'';if(!d)throw new Error('Choose approve or deny.');const rr=String(reviewReason||'').trim();if(!rr)throw new Error('A review reason is required.');const ar=doc(db,'moderationAppeals',String(appealId)),as=await getDoc(ar);if(!as.exists()||as.data().status!=='open')throw new Error('This appeal is no longer available.');const a=as.data(),batch=writeBatch(db),now=new Date().toISOString();batch.update(ar,{status:d,reviewedBy:u.uid,reviewReason:rr,reviewedAtISO:now,reviewedAt:serverTimestamp()});batch.delete(doc(db,'moderationAppealLocks',a.appellantUserId));if(d==='approved')batch.update(doc(db,'platformEnforcement',a.appellantUserId),{status:'cleared',clearedBy:u.uid,clearedAtISO:now,durationHours:null,endsAtISO:null,endsAt:null,updatedAtISO:now,updatedAt:serverTimestamp()});await batch.commit()}
export async function getNativePlatformRoleRecords(){return []} export async function searchNativePlatformRoleCandidates(){return []} export async function setNativePlatformRole(){throw new Error('Role management unchanged; use the existing Foundation admin workflow.')}
