import { useEffect,useState } from 'react';
import { ActivityIndicator,Image,Pressable,SafeAreaView,StyleSheet,Text,View } from 'react-native';
import { router,useLocalSearchParams } from 'expo-router';
import BottomNav from '../../components/BottomNav';
import { getNativePublicProfile } from '../../services/profile';
import { profileAvatarUrl } from '../../../shared/profileAvatars';
import { BRAND } from '../../../shared/brand';
export default function PublicProfile(){const {userId}=useLocalSearchParams();const [p,setP]=useState(null),[loading,setLoading]=useState(true);useEffect(()=>{getNativePublicProfile(userId).then(setP).finally(()=>setLoading(false));},[userId]);const image=profileAvatarUrl(p?.avatar)||p?.photoURL||'';return <SafeAreaView style={s.safe}><View style={s.header}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹ Back</Text></Pressable><Text style={s.title}>Reader Profile</Text></View>{loading?<ActivityIndicator style={{marginTop:50}}/>:<View style={s.card}>{image?<Image source={{uri:image}} style={s.avatar}/>:<View style={s.fallback}><Text style={s.initial}>{String(p?.displayName||p?.username||'R')[0].toUpperCase()}</Text></View>}<Text style={s.name}>{p?.displayName||p?.username||'Reader'}</Text>{p?.username?<Text style={s.username}>@{p.username}</Text>:null}{p?.about?<Text style={s.about}>{p.about}</Text>:null}</View>}<BottomNav active="library"/></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:BRAND.background},header:{padding:18,backgroundColor:BRAND.surface,borderBottomWidth:1,borderBottomColor:BRAND.line},back:{color:BRAND.tealDark,fontWeight:'900'},title:{color:BRAND.ink,fontSize:24,fontWeight:'900',marginTop:8},card:{margin:18,padding:24,alignItems:'center',backgroundColor:BRAND.surface,borderWidth:1,borderColor:BRAND.line,borderRadius:22},avatar:{width:110,height:110,borderRadius:55},fallback:{width:110,height:110,borderRadius:55,backgroundColor:BRAND.teal,alignItems:'center',justifyContent:'center'},initial:{fontSize:42,fontWeight:'900',color:'#fff'},name:{fontSize:24,fontWeight:'900',color:BRAND.ink,marginTop:16},username:{color:BRAND.tealDark,marginTop:4},about:{color:BRAND.muted,lineHeight:22,textAlign:'center',marginTop:16}});
